-- 교통사고/기타돌발/공사별 지속시간 비교`

SELECT
TYPE,
EVENTTYPE,
COUNT(*) AS total_cnt,
AVG(
CASE WHEN ENDDATE IS NULL
THEN DATEDIFF('minute', STARTDATE, CURRENT_TIMESTAMP)
ELSE DATEDIFF('minute', STARTDATE, ENDDATE)
END
) AS avg_duration_min
FROM TRAFFIC_EVENT_JIYEON
GROUP BY TYPE, EVENTTYPE
ORDER BY avg_duration_min DESC;