WITH RoadTypeDurations AS (
SELECT
TYPE, -- 도로 유형 (예: '고속도로', '국도')
-- 시간 단위 지속 시간(DURATION_HOURS) 계산
ABS(DATEDIFF(SECOND,
CAST(STARTDATE AS TIMESTAMP_NTZ),
CAST(ENDDATE AS TIMESTAMP_NTZ))) / 3600.0 AS DURATION_HOURS
FROM
TRAFFIC_EVENT_JIYEON -- 실제 테이블 이름으로 변경
WHERE
TYPE IS NOT NULL -- TYPE이 NULL인 행은 제외하고 계산합니다.
)
SELECT
TYPE AS ROAD_TYPE,
AVG(DURATION_HOURS) AS AVERAGE_DURATION_HOURS
FROM
RoadTypeDurations
GROUP BY
ROAD_TYPE
ORDER BY
AVERAGE_DURATION_HOURS DESC; -- 평균 지속 시간이 긴 순서로 정렬