-- 지속시간 계산 테이블`

SELECT
TYPE,
EVENTTYPE,
EVENTDETAILTYPE,
STARTDATE,
ENDDATE,
CASE
WHEN ENDDATE IS NULL THEN DATEDIFF('minute', STARTDATE, CURRENT_TIMESTAMP)
ELSE DATEDIFF('minute', STARTDATE, ENDDATE)
END AS duration_minutes
FROM TRAFFIC_EVENT_JIYEON;