-- 이벤트 유형별 평균/최대/최소 지속시간 분석`

SELECT
EVENTTYPE,
COUNT(*) AS event_count,
AVG(
CASE WHEN ENDDATE IS NULL
THEN DATEDIFF('minute', STARTDATE, CURRENT_TIMESTAMP)
ELSE DATEDIFF('minute', STARTDATE, ENDDATE)
END
) AS avg_duration_min,
MIN(
CASE WHEN ENDDATE IS NULL
THEN DATEDIFF('minute', STARTDATE, CURRENT_TIMESTAMP)
ELSE DATEDIFF('minute', STARTDATE, ENDDATE)
END
) AS min_duration_min,
MAX(
CASE WHEN ENDDATE IS NULL
THEN DATEDIFF('minute', STARTDATE, CURRENT_TIMESTAMP)
ELSE DATEDIFF('minute', STARTDATE, ENDDATE)
END
) AS max_duration_min
FROM TRAFFIC_EVENT_JIYEON
GROUP BY EVENTTYPE
ORDER BY avg_duration_min DESC;